use crate::ast::*;

/// Rust code generator from FSL AST
pub struct RustCodegen;

impl RustCodegen {
    /// Generate Rust source code as a String
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();

        // File header
        let desc = schema
            .description
            .as_deref()
            .unwrap_or(&schema.name);
        out.push_str(&format!(
            "// Auto-generated by fig-usl from schema '{}' v{}\n",
            schema.name, schema.version
        ));
        out.push_str(&format!("// {}\n\n", desc));

        out.push_str("use serde::{{Deserialize, Serialize}};\n\n");

        // Schema-level constants
        if let Some(id) = schema.well_known_id {
            out.push_str(&format!(
                "/// Well-known schema ID\npub const SCHEMA_ID: u8 = {:#04x};\n\n",
                id
            ));
        }

        // Generate type definitions (aliases first, then structs)
        for td in &schema.type_defs {
            if td.fields.is_none() {
                out.push_str(&Self::generate_type_alias(td));
                out.push('\n');
            }
        }

        // Generate struct type definitions
        for td in &schema.type_defs {
            if td.fields.is_some() {
                out.push_str(&Self::generate_struct_type(td));
                out.push('\n');
            }
        }

        // Collect all inline enums for forward generation
        // From messages: name = MessageName + FieldName (e.g., NewOrderSingleSide)
        let mut enum_names = std::collections::HashMap::new();
        for msg in &schema.messages {
            for field in &msg.fields {
                if let FieldType::Enum(enum_def) = &field.field_type {
                    let enum_name = format!("{}{}", msg.name, pascal_case(&field.name));
                    enum_names.entry(enum_name).or_insert_with(|| enum_def.clone());
                }
            }
        }

        // From struct type definitions: name = TypeName + FieldName
        for td in &schema.type_defs {
            if let Some(fields) = &td.fields {
                for field in fields {
                    if let FieldType::Enum(enum_def) = &field.field_type {
                        let enum_name = format!("{}{}", td.name, pascal_case(&field.name));
                        enum_names.entry(enum_name).or_insert_with(|| enum_def.clone());
                    }
                }
            }
        }

        // Collect inline structs from messages and type defs
        let mut inline_struct_names = std::collections::HashMap::new();
        for msg in &schema.messages {
            for field in &msg.fields {
                if let FieldType::InlineStruct(fields) = &field.field_type {
                    let struct_name = format!("{}{}", msg.name, pascal_case(&field.name));
                    inline_struct_names.entry(struct_name).or_insert_with(|| fields.clone());
                }
            }
        }
        for td in &schema.type_defs {
            if let Some(td_fields) = &td.fields {
                for field in td_fields {
                    if let FieldType::InlineStruct(fields) = &field.field_type {
                        let struct_name = format!("{}{}", td.name, pascal_case(&field.name));
                        inline_struct_names.entry(struct_name).or_insert_with(|| fields.clone());
                    }
                }
            }
        }

        // Generate enums
        for (name, enum_def) in &enum_names {
            out.push_str(&Self::generate_enum(name, &enum_def.variants));
            out.push('\n');
        }

        // Generate inline structs
        for (name, fields) in &inline_struct_names {
            out.push_str(&Self::generate_inline_struct(name, fields));
            out.push('\n');
        }

        // Build a combined lookup for field type resolution
        let named_types = enum_names.clone();

        // Generate message structs
        for msg in &schema.messages {
            out.push_str(&Self::generate_message(msg, &named_types));
            out.push('\n');
        }

        out
    }

    fn generate_type_alias(td: &TypeDef) -> String {
        let mut out = String::new();

        // Doc comment with constraints
        let constraint_strs: Vec<String> = td
            .constraints
            .iter()
            .map(Self::constraint_to_string)
            .collect();
        if !constraint_strs.is_empty() {
            out.push_str(&format!(
                "/// Type: {}\n/// Constraints: {}\n",
                td.name,
                constraint_strs.join(", ")
            ));
        } else {
            out.push_str(&format!("/// Type: {}\n", td.name));
        }

        let rust_type = td
            .base_type
            .as_ref()
            .map(|b| Self::base_type_to_rust(b))
            .unwrap_or_else(|| "String".to_string());

        out.push_str(&format!("pub type {} = {};\n", td.name, rust_type));
        out
    }

    fn generate_struct_type(td: &TypeDef) -> String {
        let mut out = String::new();
        let fields = td.fields.as_ref().unwrap();

        out.push_str(&format!("/// Struct type: {}\n", td.name));
        out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        out.push_str(&format!("pub struct {} {{\n", td.name));

        for field in fields {
            out.push_str(&Self::generate_field_decl(field, &td.name, "    "));
        }

        out.push_str("}\n");
        out
    }

    fn generate_message(msg: &Message, enum_names: &std::collections::HashMap<String, EnumDef>) -> String {
        let mut out = String::new();

        // Doc comment
        out.push_str(&format!(
            "/// Message: {} (channel: {:?}, priority: {:?})\n",
            msg.name, msg.channel_type, msg.priority
        ));
        if let Some(cf) = &msg.correlation_field {
            out.push_str(&format!("/// Correlation field: {}\n", cf));
        }
        if !msg.idempotent {
            out.push_str("/// NOT idempotent\n");
        }

        out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        out.push_str(&format!("pub struct {} {{\n", msg.name));

        for field in &msg.fields {
            out.push_str(&Self::generate_message_field_decl(field, msg, enum_names, "    "));
        }

        out.push_str("}\n\n");

        // Associated constants
        out.push_str(&format!("impl {} {{\n", msg.name));
        out.push_str(&format!(
            "    /// Channel type for this message\n    pub const CHANNEL_TYPE: &str = {:?};\n",
            Self::channel_type_str(&msg.channel_type)
        ));
        if let Some(cf) = &msg.correlation_field {
            out.push_str(&format!(
                "    /// Correlation field name\n    pub const CORRELATION_FIELD: &str = {:?};\n",
                cf
            ));
        }
        out.push_str(&format!(
            "    /// Priority level\n    pub const PRIORITY: &str = {:?};\n",
            Self::priority_str(&msg.priority)
        ));
        out.push_str(&format!(
            "    /// Whether this message is idempotent\n    pub const IDEMPOTENT: bool = {};\n",
            msg.idempotent
        ));
        out.push_str("}\n");

        out
    }

    fn generate_field_decl(field: &Field, parent_name: &str, indent: &str) -> String {
        let mut out = String::new();
        let rust_type = match &field.field_type {
            FieldType::Enum(_) => {
                format!("{}{}", parent_name, pascal_case(&field.name))
            }
            FieldType::InlineStruct(_) => {
                format!("{}{}", parent_name, pascal_case(&field.name))
            }
            _ => Self::field_type_to_rust(&field.field_type),
        };

        if field.optional {
            out.push_str(&format!(
                "{}#[serde(skip_serializing_if = \"Option::is_none\")]\n",
                indent
            ));
            out.push_str(&format!("{}pub {}: Option<{}>,\n", indent, field.name, rust_type));
        } else {
            out.push_str(&format!("{}pub {}: {},\n", indent, field.name, rust_type));
        }
        out
    }

    fn generate_message_field_decl(
        field: &Field,
        msg: &Message,
        enum_names: &std::collections::HashMap<String, EnumDef>,
        indent: &str,
    ) -> String {
        let mut out = String::new();

        // For inline enums and inline structs, the generated name is based on message + field
        let rust_type = match &field.field_type {
            FieldType::Enum(_) => {
                let enum_name = format!("{}{}", msg.name, pascal_case(&field.name));
                if enum_names.contains_key(&enum_name) {
                    enum_name
                } else {
                    Self::field_type_to_rust(&field.field_type)
                }
            }
            FieldType::InlineStruct(_) => {
                let struct_name = format!("{}{}", msg.name, pascal_case(&field.name));
                struct_name
            }
            _ => Self::field_type_to_rust(&field.field_type),
        };

        if field.optional {
            out.push_str(&format!(
                "{}#[serde(skip_serializing_if = \"Option::is_none\")]\n",
                indent
            ));
            out.push_str(&format!("{}pub {}: Option<{}>,\n", indent, field.name, rust_type));
        } else {
            out.push_str(&format!("{}pub {}: {},\n", indent, field.name, rust_type));
        }
        out
    }

    fn generate_enum(name: &str, variants: &[String]) -> String {
        let mut out = String::new();
        out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]\n");
        out.push_str("#[serde(rename_all = \"snake_case\")]\n");
        out.push_str(&format!("pub enum {} {{\n", name));
        for (i, v) in variants.iter().enumerate() {
            let pascal = pascal_case(v);
            out.push_str(&format!("    {} = {},\n", pascal, i + 1));
        }
        out.push_str("}\n\n");

        // from_value / to_value impl
        out.push_str(&format!("impl {} {{\n", name));
        out.push_str(&format!("    pub fn from_value(v: u8) -> Option<Self> {{\n"));
        out.push_str(        "        match v {\n");
        for (i, v) in variants.iter().enumerate() {
            let pascal = pascal_case(v);
            out.push_str(&format!("            {} => Some({}::{}),\n", i + 1, name, pascal));
        }
        out.push_str(        "            _ => None,\n");
        out.push_str(        "        }\n");
        out.push_str(        "    }\n\n");
        out.push_str(&format!("    pub fn to_value(self) -> u8 {{\n"));
        out.push_str(        "        self as u8\n");
        out.push_str(        "    }}\n");
        out.push_str("}\n");
        out
    }

    fn generate_inline_struct(name: &str, fields: &[Field]) -> String {
        let mut out = String::new();
        out.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
        out.push_str(&format!("pub struct {} {{\n", name));
        for field in fields {
            let rust_type = Self::field_type_to_rust(&field.field_type);
            if field.optional {
                out.push_str(&format!("    pub {}: Option<{}>,\n", field.name, rust_type));
            } else {
                out.push_str(&format!("    pub {}: {},\n", field.name, rust_type));
            }
        }
        out.push_str("}\n\n");

        // ENCODED_LEN constant
        let encoded_len: usize = fields.iter().map(|f| Self::field_encoded_size(&f.field_type)).sum();
        out.push_str(&format!("impl {} {{\n", name));
        out.push_str(&format!("    pub const ENCODED_LEN: usize = {}; // ", encoded_len));
        let sizes: Vec<String> = fields.iter()
            .map(|f| format!("{}", Self::field_encoded_size(&f.field_type)))
            .collect();
        out.push_str(&sizes.join(" + "));
        out.push_str("\n}\n");
        out
    }

    // ── Type mapping helpers ──────────────────────────────────

    fn base_type_to_rust(bt: &BaseType) -> String {
        match bt {
            BaseType::String => "String".to_string(),
            BaseType::Int8 => "i8".to_string(),
            BaseType::Int16 => "i16".to_string(),
            BaseType::Int32 => "i32".to_string(),
            BaseType::Int64 => "i64".to_string(),
            BaseType::UInt8 => "u8".to_string(),
            BaseType::UInt16 => "u16".to_string(),
            BaseType::UInt32 => "u32".to_string(),
            BaseType::UInt64 => "u64".to_string(),
            BaseType::Float32 => "f32".to_string(),
            BaseType::Float64 => "f64".to_string(),
            BaseType::Decimal64 => "f64".to_string(),
            BaseType::Bool => "bool".to_string(),
            BaseType::Bytes => "Vec<u8>".to_string(),
            BaseType::List(inner) => format!("Vec<{}>", Self::base_type_to_rust(inner)),
        }
    }

    fn field_type_to_rust(ft: &FieldType) -> String {
        match ft {
            FieldType::Named(name) => name.clone(),
            FieldType::Enum(_) => "u8".to_string(), // fallback; resolved in context
            FieldType::List(inner) => {
                format!("Vec<{}>", Self::field_type_to_rust(inner))
            }
            FieldType::InlineStruct(_) => "()".to_string(), // fallback; resolved in context
            FieldType::InlineBase(bt, _) => Self::base_type_to_rust(bt),
        }
    }

    /// Return the encoded byte size of a field type (for SBE block length).
    fn field_encoded_size(ft: &FieldType) -> usize {
        match ft {
            FieldType::Named(name) => {
                match name.as_str() {
                    "String" | "Vec<u8>" | "ClientOrderId" | "Symbol" => 0, // variable-length
                    "Price" | "Quantity" => 8, // f64
                    "TradeTimestamp" | "i64" | "u64" => 8,
                    "i32" | "u32" | "f32" => 4,
                    "i16" | "u16" => 2,
                    "i8" | "u8" | "bool" => 1,
                    "f64" => 8,
                    _ => 0, // unknown, assume variable
                }
            }
            FieldType::Enum(_) => 1, // u8 enum
            FieldType::List(_) => 0, // variable-length group
            FieldType::InlineStruct(fields) => {
                fields.iter().map(|f| Self::field_encoded_size(&f.field_type)).sum()
            }
            FieldType::InlineBase(bt, _) => {
                match bt {
                    BaseType::String | BaseType::Bytes => 0,
                    BaseType::Int8 | BaseType::UInt8 | BaseType::Bool => 1,
                    BaseType::Int16 | BaseType::UInt16 => 2,
                    BaseType::Int32 | BaseType::UInt32 | BaseType::Float32 => 4,
                    BaseType::Int64 | BaseType::UInt64 | BaseType::Float64 | BaseType::Decimal64 => 8,
                    BaseType::List(_) => 0,
                }
            }
        }
    }

    fn constraint_to_string(c: &Constraint) -> String {
        match c {
            Constraint::MaxLen(n) => format!("max_len: {}", n),
            Constraint::Min(v) => format!("min: {}", v),
            Constraint::Max(v) => format!("max: {}", v),
            Constraint::Precision(n) => format!("precision: {}", n),
            Constraint::Pattern(s) => format!("pattern: {:?}", s),
            Constraint::Uppercase(b) => format!("uppercase: {}", b),
        }
    }

    fn channel_type_str(ct: &ChannelType) -> &'static str {
        match ct {
            ChannelType::RequestResponse => "request_response",
            ChannelType::StreamItem => "stream_item",
            ChannelType::BidirectionalStream => "bidirectional_stream",
            ChannelType::FireAndForget => "fire_and_forget",
            ChannelType::PubSub => "pub_sub",
        }
    }

    fn priority_str(p: &Priority) -> &'static str {
        match p {
            Priority::High => "high",
            Priority::Medium => "medium",
            Priority::Low => "low",
        }
    }
}

/// Convert a snake_case identifier to PascalCase
fn pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::Parser;

    #[test]
    fn test_pascal_case() {
        assert_eq!(pascal_case("buy"), "Buy");
        assert_eq!(pascal_case("sell_short"), "SellShort");
        assert_eq!(pascal_case("done_for_day"), "DoneForDay");
        assert_eq!(pascal_case("gtc"), "Gtc");
    }

    #[test]
    fn test_generate_simple_schema() {
        let input = r#"
            schema test v1.0 {
                description: "Test schema"
                well_known_id: 0x01
                type Name: string(max_len: 32)
                message Greeting {
                    channel_type: request_response
                    name: Name @1
                    language: enum { en, fr, de } @2
                }
            }
        "#;
        let schema = Parser::parse(input).unwrap();
        let code = RustCodegen::generate(&schema);

        // Should contain expected elements
        assert!(code.contains("pub type Name = String;"));
        assert!(code.contains("pub struct Greeting"));
        assert!(code.contains("pub name: Name,"));
        assert!(code.contains("pub language: GreetingLanguage,"));
        assert!(code.contains("pub enum GreetingLanguage"));
        assert!(code.contains("    En = 1,"));
        assert!(code.contains("    Fr = 2,"));
        assert!(code.contains("    De = 3,"));
        assert!(code.contains("#[serde(rename_all = \"snake_case\")]"));
        assert!(code.contains("pub const SCHEMA_ID: u8 = 0x01;"));
        assert!(code.contains("pub const CHANNEL_TYPE: &str = \"request_response\";"));
    }

    #[test]
    fn test_generate_with_optional() {
        let input = r#"
            schema x v1 {
                message M {
                    channel_type: stream_item
                    a: string(max_len: 10) @1
                    b: string(max_len: 10) @2 optional
                }
            }
        "#;
        let schema = Parser::parse(input).unwrap();
        let code = RustCodegen::generate(&schema);
        assert!(code.contains("pub a: String,"));
        assert!(code.contains("pub b: Option<String>,"));
        assert!(code.contains("skip_serializing_if"));
    }

    #[test]
    fn test_generate_struct_type() {
        let input = r#"
            schema x v1 {
                type PriceLevel {
                    price: Price
                    qty: Quantity
                    count: uint32 optional
                }
            }
        "#;
        let schema = Parser::parse(input).unwrap();
        let code = RustCodegen::generate(&schema);
        assert!(code.contains("pub struct PriceLevel"));
        assert!(code.contains("pub price: Price,"));
        assert!(code.contains("pub qty: Quantity,"));
        assert!(code.contains("pub count: Option<u32>,"));
    }

    #[test]
    fn test_generate_full_orders() {
        let orders_path = env!("CARGO_MANIFEST_DIR").to_string() + "/../../schemas/orders.usl";
        let input = std::fs::read_to_string(orders_path).unwrap();
        let schema = Parser::parse(&input).unwrap();
        let code = RustCodegen::generate(&schema);

        // Verify key types and messages are generated
        assert!(code.contains("pub type ClientOrderId = String;"));
        assert!(code.contains("pub type Price = f64;"));
        assert!(code.contains("pub type Quantity = f64;"));
        assert!(code.contains("pub type Symbol = String;"));
        assert!(code.contains("pub type TradeTimestamp = i64;"));
        assert!(code.contains("pub struct NewOrderSingle"));
        assert!(code.contains("pub struct CancelRequest"));
        assert!(code.contains("pub struct ExecutionReport"));
        assert!(code.contains("pub struct MarketDataSnapshot"));
        assert!(code.contains("pub struct PriceLevel"));
        assert!(code.contains("pub struct MarketDataUpdate"));
        assert!(code.contains("pub enum NewOrderSingleSide"));
        assert!(code.contains("pub enum NewOrderSingleOrderType"));
        assert!(code.contains("pub cl_ord_id: ClientOrderId,"));
        assert!(code.contains("pub order_qty: Quantity,"));
    }

    #[test]
    fn test_generated_code_is_valid_rust_structure() {
        // Test that the generated code has valid Rust syntax structure
        let input = r#"
            schema test v1.0 {
                type Id: string(max_len: 32)
                message Order {
                    channel_type: request_response
                    correlation_field: id
                    id: Id @1
                    side: enum { buy, sell } @2
                    price: decimal64(precision: 8, min: 0) @3 optional
                    priority: high
                    idempotent: false
                }
            }
        "#;
        let schema = Parser::parse(input).unwrap();
        let code = RustCodegen::generate(&schema);

        // Verify derive macros are present on all types
        assert!(code.contains("#[derive(Debug, Clone, Serialize, Deserialize)]"));
        // Verify idempotent const
        assert!(code.contains("pub const IDEMPOTENT: bool = false;"));
        // Verify correlation field
        assert!(code.contains("pub const CORRELATION_FIELD: &str = \"id\";"));
        // Verify priority
        assert!(code.contains("pub const PRIORITY: &str = \"high\";"));
    }
}
