//! Hardcoded message types for the FIG exchange simulator.
//!
//! These are manually defined structs that mirror the FSL schema in
//! schemas/orders.fsl. In production, these would be generated by
//! the FSL codegen tool (fig-fsl). For the skeleton demo, we
//! hardcode them to avoid a dependency on codegen during early development.

use serde::{Deserialize, Serialize};

// ─── Custom Types ───────────────────────────────────────────────

pub type ClientOrderId = String;
pub type Symbol = String;
pub type TradeTimestamp = i64; // nanoseconds since Unix epoch

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Price(pub f64);

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Quantity(pub f64);

// ─── Enums ──────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum Side {
    Buy,
    Sell,
    SellShort,
    SellShortExempt,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum OrderType {
    Market,
    Limit,
    Stop,
    StopLimit,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum TimeInForce {
    Day,
    Gtc,
    Ioc,
    Fok,
    Gtd,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ExecType {
    New,
    PartialFill,
    Fill,
    DoneForDay,
    Canceled,
    Replaced,
    PendingCancel,
    Stopped,
    Rejected,
    Suspended,
    PendingNew,
    Expired,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum OrdStatus {
    New,
    PartiallyFilled,
    Filled,
    DoneForDay,
    Canceled,
    PendingCancel,
    Stopped,
    Rejected,
    Suspended,
    PendingNew,
    Expired,
    Replaced,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum CancelRejectReason {
    OrderNotFound,
    AlreadyCanceled,
    AlreadyFilled,
    TooLateToCancel,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum MarketDataAction {
    New,
    Change,
    Delete,
}

// ─── Messages ───────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct NewOrderSingle {
    pub cl_ord_id: ClientOrderId,
    pub side: Side,
    pub order_qty: Quantity,
    pub price: Option<Price>,
    pub stop_price: Option<Price>,
    pub symbol: Symbol,
    pub order_type: OrderType,
    pub time_in_force: TimeInForce,
    pub expire_time: Option<TradeTimestamp>,
    pub account: Option<String>,
    pub strategy_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CancelRequest {
    pub cl_ord_id: ClientOrderId,
    pub orig_cl_ord_id: ClientOrderId,
    pub symbol: Symbol,
    pub side: Side,
    pub order_qty: Option<Quantity>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CancelReplaceRequest {
    pub cl_ord_id: ClientOrderId,
    pub orig_cl_ord_id: ClientOrderId,
    pub symbol: Symbol,
    pub side: Side,
    pub order_qty: Quantity,
    pub price: Option<Price>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ExecutionReport {
    pub cl_ord_id: ClientOrderId,
    pub order_id: String,
    pub exec_id: String,
    pub exec_type: ExecType,
    pub ord_status: OrdStatus,
    pub side: Side,
    pub last_qty: Option<Quantity>,
    pub last_price: Option<Price>,
    pub leaves_qty: Quantity,
    pub cum_qty: Quantity,
    pub avg_price: Price,
    pub symbol: Symbol,
    pub transact_time: TradeTimestamp,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CancelReject {
    pub cl_ord_id: ClientOrderId,
    pub orig_cl_ord_id: ClientOrderId,
    pub reject_reason: CancelRejectReason,
    pub symbol: Symbol,
}

// ─── Market Data ─────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PriceLevel {
    pub price: Price,
    pub qty: Quantity,
    pub order_count: Option<u32>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct MarketDataUpdate {
    pub side: Side,
    pub action: MarketDataAction,
    pub price: Price,
    pub qty: Quantity,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct MarketDataSnapshot {
    pub symbol: Symbol,
    pub exchange: String,
    pub bids: Vec<PriceLevel>,
    pub asks: Vec<PriceLevel>,
    pub timestamp: TradeTimestamp,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct MarketDataIncrementalRefresh {
    pub symbol: Symbol,
    pub updates: Vec<MarketDataUpdate>,
    pub timestamp: TradeTimestamp,
}

// ─── Account ─────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AccountSummary {
    pub account: String,
    pub balance: f64,
    pub buying_power: f64,
    pub currency: String,
}

// ─── Schema IDs ─────────────────────────────────────────────────

/// Well-known schema IDs for the trading messages.
/// These match the well_known_id in the FSL schema.
pub mod schema_id {
    pub const TRADING_ORDERS: u8 = 0x01;
}

// ─── Channel Paths ──────────────────────────────────────────────

/// Well-known channel paths for the exchange simulator.
pub mod channel_path {
    pub const ORDERS: &str = "trading/accounts/{account}/orders";
    pub const CANCEL: &str = "trading/accounts/{account}/orders/{order_id}/cancel";
    pub const CANCEL_REPLACE: &str = "trading/accounts/{account}/orders/{order_id}/replace";
    pub const EXECUTIONS: &str = "trading/accounts/{account}/executions";
    pub const MARKET_DATA: &str = "marketdata/{symbol}/quotes";
    pub const ACCOUNT: &str = "accounts/{account}";
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_new_order_round_trip() {
        let order = NewOrderSingle {
            cl_ord_id: "ORD-001".to_string(),
            side: Side::Buy,
            order_qty: Quantity(100.0),
            price: Some(Price(50.25)),
            stop_price: None,
            symbol: "AAPL".to_string(),
            order_type: OrderType::Limit,
            time_in_force: TimeInForce::Day,
            expire_time: None,
            account: Some("ACCT-123".to_string()),
            strategy_id: None,
        };

        // CBOR round-trip
        let mut buf = Vec::new();
        ciborium::ser::into_writer(&order, &mut buf).unwrap();
        let decoded: NewOrderSingle = ciborium::de::from_reader(&buf[..]).unwrap();
        assert_eq!(order, decoded);
    }

    #[test]
    fn test_execution_report_round_trip() {
        let report = ExecutionReport {
            cl_ord_id: "ORD-001".to_string(),
            order_id: "OX-001".to_string(),
            exec_id: "EX-001".to_string(),
            exec_type: ExecType::Fill,
            ord_status: OrdStatus::Filled,
            side: Side::Buy,
            last_qty: Some(Quantity(100.0)),
            last_price: Some(Price(50.25)),
            leaves_qty: Quantity(0.0),
            cum_qty: Quantity(100.0),
            avg_price: Price(50.25),
            symbol: "AAPL".to_string(),
            transact_time: 1700000000000000000,
        };

        let mut buf = Vec::new();
        ciborium::ser::into_writer(&report, &mut buf).unwrap();
        let decoded: ExecutionReport = ciborium::de::from_reader(&buf[..]).unwrap();
        assert_eq!(report, decoded);
    }
}
