//! Multi-target schema codegen (Go, Protobuf, SBE XML, C++, C#).
//!
//! Generates message struct definitions from FSL AST — focused on
//! `schema.messages` fields with BaseType → target type mapping.

use crate::ast::*;

/// Go struct generator with JSON tags
pub struct GoCodegen;

/// Protobuf `.proto` file generator
pub struct ProtoCodegen;

/// SBE XML `messageSchema` generator
pub struct SbeXmlCodegen;

/// C++ struct generator
pub struct CppCodegen;

/// C# class generator
pub struct CsharpCodegen;

/// Python dataclass generator
pub struct PythonCodegen;

/// TypeScript interface generator
pub struct TypeScriptCodegen;

/// OCaml record generator
pub struct OcamlCodegen;

/// Zig struct generator
pub struct ZigCodegen;

/// Java class generator
pub struct JavaCodegen;

/// JSON Schema generator
pub struct JsonSchemaCodegen;

/// FIX mapping YAML generator
pub struct FixYamlCodegen;

impl GoCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        let desc = schema.description.as_deref().unwrap_or(&schema.name);
        out.push_str(&format!(
            "// Auto-generated by fig-fsl from schema '{}' v{}\n",
            schema.name, schema.version
        ));
        out.push_str(&format!("// {}\n\n", desc));
        out.push_str("package generated\n\n");

        for td in &schema.type_defs {
            if td.fields.is_none() {
                out.push_str(&format_type_alias_comment(td));
                let base = go_type_alias_base(td);
                out.push_str(&format!("type {} {}\n\n", td.name, base));
            }
        }

        for (name, variants) in collect_shared_enums(schema) {
            out.push_str(&format!("type {name} int32\n\n"));
            out.push_str("const (\n");
            for (i, variant) in variants.iter().enumerate() {
                out.push_str(&format!(
                    "    {}{} = {}\n",
                    name,
                    pascal_case(variant),
                    i + 1
                ));
            }
            out.push_str(")\n\n");
        }

        for td in &schema.type_defs {
            if let Some(fields) = &td.fields {
                out.push_str(&format!("// Struct: {}\n", td.name));
                out.push_str(&format!("type {} struct {{\n", td.name));
                for field in fields {
                    let go_type = go_field_type_named(
                        &field.field_type,
                        schema,
                        &td.name,
                        field.optional,
                        &field.name,
                    );
                    out.push_str(&format!("    {} {}\n", pascal_case(&field.name), go_type));
                }
                out.push_str("}\n\n");
            }
        }

        for msg in &schema.messages {
            out.push_str(&format!("// Message: {}\n", msg.name));
            out.push_str(&message_metadata_constants_go(msg, schema.well_known_id));
            out.push_str(&cbor_fields_comment(msg));
            out.push_str(&format!("type {} struct {{\n", msg.name));
            for field in &msg.fields {
                let go_type = go_field_type_named(
                    &field.field_type,
                    schema,
                    &msg.name,
                    field.optional,
                    &field.name,
                );
                let field_name = pascal_case(&field.name);
                out.push_str(&format!(
                    "    {} {} `json:\"{}\" cbor:\"{}\"`\n",
                    field_name, go_type, field.name, field.name
                ));
            }
            out.push_str("}\n\n");
        }
        out
    }
}

impl ProtoCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        let desc = schema.description.as_deref().unwrap_or(&schema.name);
        out.push_str(&format!(
            "// Auto-generated by fig-fsl from schema '{}' v{}\n",
            schema.name, schema.version
        ));
        out.push_str(&format!("// {}\n\n", desc));
        out.push_str("syntax = \"proto3\";\n\n");
        out.push_str(&format!(
            "package {};\n\n",
            proto_package_name(&schema.name)
        ));

        for msg in &schema.messages {
            out.push_str(&format!("// Message: {}\n", msg.name));
            out.push_str(&format!("message {} {{\n", msg.name));
            for field in &msg.fields {
                let proto_type =
                    proto_field_type(&field.field_type, schema, &msg.name, field.optional);
                let number = field.number.unwrap_or(0);
                if field.optional {
                    out.push_str(&format!(
                        "  optional {} {} = {};\n",
                        proto_type, field.name, number
                    ));
                } else {
                    out.push_str(&format!("  {} {} = {};\n", proto_type, field.name, number));
                }
            }
            out.push_str("}\n\n");
        }
        out
    }
}

impl SbeXmlCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        let desc = schema.description.as_deref().unwrap_or(&schema.name);
        out.push_str(&format!(
            "<!-- Auto-generated by fig-fsl from schema '{}' v{} -->\n",
            schema.name, schema.version
        ));
        out.push_str(&format!("<!-- {} -->\n", desc));
        out.push_str("<sbe:messageSchema xmlns:sbe=\"http://fixprotocol.io/2016/sbe\"\n");
        out.push_str(&format!(
            "                   package=\"{}\"\n",
            schema.name.replace('.', "_")
        ));
        let schema_id = schema.well_known_id.unwrap_or(1);
        out.push_str(&format!("                   id=\"{}\"\n", schema_id));
        out.push_str("                   version=\"0\"\n");
        out.push_str(&format!(
            "                   semanticVersion=\"{}\"\n",
            schema.version
        ));
        out.push_str("                   byteOrder=\"littleEndian\">\n\n");
        out.push_str("  <types>\n");
        out.push_str("    <composite name=\"messageHeader\" description=\"Message identifiers and length of message root\">\n");
        out.push_str("      <type name=\"blockLength\" primitiveType=\"uint16\"/>\n");
        out.push_str("      <type name=\"templateId\" primitiveType=\"uint16\"/>\n");
        out.push_str("      <type name=\"schemaId\" primitiveType=\"uint16\"/>\n");
        out.push_str("      <type name=\"version\" primitiveType=\"uint16\"/>\n");
        out.push_str("    </composite>\n");
        out.push_str("  </types>\n\n");

        for (template_id, msg) in schema.messages.iter().enumerate() {
            let tid = template_id + 1;
            out.push_str(&format!(
                "  <message name=\"{}\" id=\"{}\">\n",
                msg.name, tid
            ));
            for field in &msg.fields {
                let sbe_type = sbe_xml_field_type(&field.field_type, schema);
                let presence = if field.optional {
                    "optional"
                } else {
                    "required"
                };
                let field_id = field.number.unwrap_or(0);
                let sbe_name = snake_to_camel(&field.name);
                out.push_str(&format!(
                    "    <field name=\"{}\" id=\"{}\" type=\"{}\" presence=\"{}\"/>\n",
                    sbe_name, field_id, sbe_type, presence
                ));
            }
            out.push_str("  </message>\n\n");
        }
        out.push_str("</sbe:messageSchema>\n");
        out
    }
}

impl CppCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        let desc = schema.description.as_deref().unwrap_or(&schema.name);
        out.push_str(&format!(
            "// Auto-generated by fig-fsl from schema '{}' v{}\n",
            schema.name, schema.version
        ));
        out.push_str(&format!("// {}\n\n", desc));
        out.push_str("#include <cstdint>\n");
        out.push_str("#include <optional>\n");
        out.push_str("#include <string>\n");
        out.push_str("#include <vector>\n\n");

        for (name, variants) in collect_shared_enums(schema) {
            out.push_str(&format!("enum class {name} : uint8_t {{\n"));
            for (i, variant) in variants.iter().enumerate() {
                out.push_str(&format!("    {} = {},\n", pascal_case(variant), i + 1));
            }
            out.push_str("};\n\n");
        }

        for td in &schema.type_defs {
            if let Some(fields) = &td.fields {
                out.push_str(&format!("// Struct: {}\n", td.name));
                out.push_str(&format!("struct {} {{\n", td.name));
                for field in fields {
                    let cpp_type = cpp_field_type_named(
                        &field.field_type,
                        schema,
                        &td.name,
                        field.optional,
                        &field.name,
                    );
                    out.push_str(&format!("    {} {};\n", cpp_type, field.name));
                }
                out.push_str("};\n\n");
            }
        }

        for msg in &schema.messages {
            out.push_str(&format!("// Message: {}\n", msg.name));
            out.push_str(&format!("struct {} {{\n", msg.name));
            for field in &msg.fields {
                let cpp_type = cpp_field_type_named(
                    &field.field_type,
                    schema,
                    &msg.name,
                    field.optional,
                    &field.name,
                );
                out.push_str(&format!("    {} {};\n", cpp_type, field.name));
            }
            out.push_str("};\n\n");
        }
        out
    }
}

impl CsharpCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        let desc = schema.description.as_deref().unwrap_or(&schema.name);
        out.push_str(&format!(
            "// Auto-generated by fig-fsl from schema '{}' v{}\n",
            schema.name, schema.version
        ));
        out.push_str(&format!("// {}\n\n", desc));
        out.push_str("using System.Collections.Generic;\n\n");
        out.push_str("namespace Generated\n{\n");

        for (name, variants) in collect_shared_enums(schema) {
            out.push_str(&format!("    public enum {}\n", name));
            out.push_str("    {\n");
            for (i, variant) in variants.iter().enumerate() {
                out.push_str(&format!("        {} = {},\n", pascal_case(variant), i + 1));
            }
            out.push_str("    }\n\n");
        }

        for td in &schema.type_defs {
            if let Some(fields) = &td.fields {
                out.push_str(&format!("    // Struct: {}\n", td.name));
                out.push_str(&format!("    public class {}\n", td.name));
                out.push_str("    {\n");
                for field in fields {
                    let cs_type = csharp_field_type_named(
                        &field.field_type,
                        schema,
                        &td.name,
                        field.optional,
                        &field.name,
                    );
                    let prop_name = snake_to_camel(&field.name);
                    out.push_str(&format!(
                        "        public {} {} {{ get; set; }}\n",
                        cs_type, prop_name
                    ));
                }
                out.push_str("    }\n\n");
            }
        }

        for msg in &schema.messages {
            out.push_str(&format!("    // Message: {}\n", msg.name));
            out.push_str(&format!("    public class {}\n", msg.name));
            out.push_str("    {\n");
            for field in &msg.fields {
                let cs_type = csharp_field_type_named(
                    &field.field_type,
                    schema,
                    &msg.name,
                    field.optional,
                    &field.name,
                );
                let prop_name = snake_to_camel(&field.name);
                out.push_str(&format!(
                    "        public {} {} {{ get; set; }}\n",
                    cs_type, prop_name
                ));
            }
            out.push_str("    }\n\n");
        }
        out.push_str("}\n");
        out
    }
}

// ── Shared helpers ──────────────────────────────────────────────

fn canonical_enum_name(field_name: &str, parent: &str) -> String {
    match field_name {
        "side" => "Side".to_string(),
        "order_type" => "OrderType".to_string(),
        "time_in_force" => "TimeInForce".to_string(),
        "id_source" => "SecurityIdSource".to_string(),
        "exec_type" => "ExecType".to_string(),
        "ord_status" => "OrdStatus".to_string(),
        "reject_reason" => "CancelRejectReason".to_string(),
        "action" if parent.contains("MarketData") => "MarketDataAction".to_string(),
        other => format!("{}{}", parent, pascal_case(other)),
    }
}

fn merge_enum_variants(
    map: &mut std::collections::HashMap<String, Vec<String>>,
    name: String,
    variants: &[String],
) {
    map.entry(name)
        .and_modify(|existing| {
            for v in variants {
                if !existing.contains(v) {
                    existing.push(v.clone());
                }
            }
        })
        .or_insert_with(|| variants.to_vec());
}

fn collect_shared_enums(schema: &Schema) -> Vec<(String, Vec<String>)> {
    let mut enums = std::collections::HashMap::new();
    for msg in &schema.messages {
        for field in &msg.fields {
            if let FieldType::Enum(enum_def) = &field.field_type {
                let name = canonical_enum_name(&field.name, &msg.name);
                merge_enum_variants(&mut enums, name, &enum_def.variants);
            }
        }
    }
    for td in &schema.type_defs {
        if let Some(fields) = &td.fields {
            for field in fields {
                if let FieldType::Enum(enum_def) = &field.field_type {
                    let name = canonical_enum_name(&field.name, &td.name);
                    merge_enum_variants(&mut enums, name, &enum_def.variants);
                }
            }
        }
    }
    let mut out: Vec<_> = enums.into_iter().collect();
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

fn channel_type_str(ct: &ChannelType) -> &'static str {
    match ct {
        ChannelType::RequestResponse => "request_response",
        ChannelType::StreamItem => "stream_item",
        ChannelType::BidirectionalStream => "bidirectional_stream",
        ChannelType::FireAndForget => "fire_and_forget",
        ChannelType::PubSub => "pub_sub",
    }
}

fn format_type_alias_comment(td: &TypeDef) -> String {
    if td.constraints.is_empty() {
        format!("// Type: {}\n", td.name)
    } else {
        let constraints: Vec<String> = td.constraints.iter().map(constraint_to_doc).collect();
        format!("// Type: {} — {}\n", td.name, constraints.join(", "))
    }
}

fn constraint_to_doc(c: &Constraint) -> String {
    match c {
        Constraint::MaxLen(n) => format!("max_len: {n}"),
        Constraint::Min(v) => format!("min: {v}"),
        Constraint::Max(v) => format!("max: {v}"),
        Constraint::Precision(n) => format!("precision: {n}"),
        Constraint::Pattern(p) => format!("pattern: {p:?}"),
        Constraint::Uppercase(b) => format!("uppercase: {b}"),
    }
}

fn type_alias_base_name(td: &TypeDef) -> &'static str {
    match td.base_type.as_ref() {
        Some(BaseType::String | BaseType::Bytes) => "string",
        Some(BaseType::Bool) => "bool",
        Some(BaseType::Float32 | BaseType::Float64 | BaseType::Decimal64) => "float64",
        Some(BaseType::Int64 | BaseType::UInt64) => "int64",
        Some(
            BaseType::Int8
            | BaseType::Int16
            | BaseType::Int32
            | BaseType::UInt8
            | BaseType::UInt16
            | BaseType::UInt32,
        ) => "int32",
        Some(BaseType::List(_)) => "list",
        None => "string",
    }
}

fn go_type_alias_base(td: &TypeDef) -> &'static str {
    match type_alias_base_name(td) {
        "string" => "string",
        "bool" => "bool",
        "float64" => "float64",
        "int64" => "int64",
        "int32" => "int32",
        "list" => "[]string",
        _ => "string",
    }
}

fn ts_type_alias_base(td: &TypeDef) -> &'static str {
    match type_alias_base_name(td) {
        "string" => "string",
        "bool" => "boolean",
        "float64" | "int32" | "int64" => "number",
        "list" => "string[]",
        _ => "string",
    }
}

fn ocaml_type_alias_base(td: &TypeDef) -> &'static str {
    match type_alias_base_name(td) {
        "string" => "string",
        "bool" => "bool",
        "float64" => "float",
        "int64" => "int64",
        "int32" => "int",
        "list" => "string list",
        _ => "string",
    }
}

fn zig_type_alias_base(td: &TypeDef) -> &'static str {
    match type_alias_base_name(td) {
        "string" => "[]const u8",
        "bool" => "bool",
        "float64" => "f64",
        "int64" => "i64",
        "int32" => "i32",
        "list" => "[]const []const u8",
        _ => "[]const u8",
    }
}

fn java_type_alias_base(td: &TypeDef) -> &'static str {
    match type_alias_base_name(td) {
        "string" => "String",
        "bool" => "boolean",
        "float64" => "double",
        "int64" => "long",
        "int32" => "int",
        "list" => "List<String>",
        _ => "String",
    }
}

fn cbor_fields_comment(msg: &Message) -> String {
    let fields: Vec<&str> = msg.fields.iter().map(|f| f.name.as_str()).collect();
    format!(
        "// CBOR (snake_case keys, string enums): {}\n",
        fields.join(", ")
    )
}

fn message_metadata_constants_go(msg: &Message, schema_id: Option<u8>) -> String {
    let mut out = format!(
        "const (\n    {}MessageName = \"{}\"\n    {}ChannelType = \"{}\"\n",
        msg.name,
        msg.name,
        msg.name,
        channel_type_str(&msg.channel_type)
    );
    if let Some(cf) = &msg.correlation_field {
        out.push_str(&format!("    {}CorrelationField = \"{cf}\"\n", msg.name));
    }
    if let Some(id) = schema_id {
        out.push_str(&format!("    {}SchemaId = 0x{id:02x}\n", msg.name));
    }
    out.push_str(")\n");
    out
}

fn message_metadata_constants_ts(msg: &Message, schema_id: Option<u8>) -> String {
    let mut out = format!(
        "export const {}MessageName = \"{}\" as const;\nexport const {}ChannelType = \"{}\" as const;\n",
        msg.name, msg.name, msg.name, channel_type_str(&msg.channel_type)
    );
    if let Some(cf) = &msg.correlation_field {
        out.push_str(&format!(
            "export const {}CorrelationField = \"{cf}\" as const;\n",
            msg.name
        ));
    }
    if let Some(id) = schema_id {
        out.push_str(&format!(
            "export const {}SchemaId = 0x{id:02x} as const;\n",
            msg.name
        ));
    }
    out.push_str(&cbor_fields_comment(msg));
    out
}

fn python_field_type_named(
    ft: &FieldType,
    schema: &Schema,
    optional: bool,
    parent: &str,
    field_name: &str,
) -> String {
    let base = match ft {
        FieldType::Named(name) => {
            if schema
                .type_defs
                .iter()
                .any(|td| td.name == *name && td.fields.is_some())
            {
                name.clone()
            } else if let Some(bt) = resolve_named_type(name, schema) {
                python_base_type(&bt)
            } else {
                "str".to_string()
            }
        }
        FieldType::Enum(_) => canonical_enum_name(field_name, parent),
        FieldType::List(inner) => format!(
            "list[{}]",
            python_field_type_named(inner, schema, false, parent, field_name)
        ),
        FieldType::InlineStruct(_) => "dict".to_string(),
        FieldType::InlineBase(bt, _) => python_base_type(bt),
    };
    if optional {
        format!("Optional[{base}]")
    } else {
        base
    }
}

fn go_field_type_named(
    ft: &FieldType,
    schema: &Schema,
    parent: &str,
    optional: bool,
    field_name: &str,
) -> String {
    let base = match ft {
        FieldType::Named(name) => {
            if schema
                .type_defs
                .iter()
                .any(|td| td.name == *name && td.fields.is_some())
            {
                name.clone()
            } else if let Some(bt) = resolve_named_type(name, schema) {
                go_base_type(&bt)
            } else {
                match name.as_str() {
                    "Price" | "Quantity" => "float64".to_string(),
                    "TradeTimestamp" => "int64".to_string(),
                    _ => "string".to_string(),
                }
            }
        }
        FieldType::Enum(_) => canonical_enum_name(field_name, parent),
        FieldType::List(inner) => {
            format!(
                "[]{}",
                go_field_type_named(inner, schema, parent, false, field_name)
            )
        }
        FieldType::InlineStruct(_) => parent.to_string(),
        FieldType::InlineBase(bt, _) => go_base_type(bt),
    };
    if optional {
        format!("*{base}")
    } else {
        base
    }
}

fn pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

fn snake_to_camel(s: &str) -> String {
    let parts: Vec<&str> = s.split('_').collect();
    if parts.is_empty() {
        return String::new();
    }
    let first = parts[0];
    let rest = parts
        .iter()
        .skip(1)
        .map(|p| pascal_case(p))
        .collect::<Vec<_>>()
        .join("");
    format!("{}{}", first, rest)
}

fn proto_package_name(name: &str) -> String {
    name.replace('.', "_")
}

fn resolve_named_type(name: &str, schema: &Schema) -> Option<BaseType> {
    schema
        .type_defs
        .iter()
        .find(|td| td.name == name)
        .and_then(|td| td.base_type.clone())
}

fn go_base_type(bt: &BaseType) -> String {
    match bt {
        BaseType::String => "string".to_string(),
        BaseType::Int8 => "int8".to_string(),
        BaseType::Int16 => "int16".to_string(),
        BaseType::Int32 => "int32".to_string(),
        BaseType::Int64 => "int64".to_string(),
        BaseType::UInt8 => "uint8".to_string(),
        BaseType::UInt16 => "uint16".to_string(),
        BaseType::UInt32 => "uint32".to_string(),
        BaseType::UInt64 => "uint64".to_string(),
        BaseType::Float32 => "float32".to_string(),
        BaseType::Float64 => "float64".to_string(),
        BaseType::Decimal64 => "float64".to_string(),
        BaseType::Bool => "bool".to_string(),
        BaseType::Bytes => "[]byte".to_string(),
        BaseType::List(inner) => format!("[]{}", go_base_type(inner)),
    }
}

fn proto_base_type(bt: &BaseType) -> String {
    match bt {
        BaseType::String => "string".to_string(),
        BaseType::Int8 | BaseType::Int16 | BaseType::Int32 => "int32".to_string(),
        BaseType::Int64 => "int64".to_string(),
        BaseType::UInt8 | BaseType::UInt16 | BaseType::UInt32 => "uint32".to_string(),
        BaseType::UInt64 => "uint64".to_string(),
        BaseType::Float32 => "float".to_string(),
        BaseType::Float64 | BaseType::Decimal64 => "double".to_string(),
        BaseType::Bool => "bool".to_string(),
        BaseType::Bytes => "bytes".to_string(),
        BaseType::List(inner) => format!("repeated {}", proto_base_type(inner)),
    }
}

fn proto_field_type(ft: &FieldType, schema: &Schema, msg_name: &str, _optional: bool) -> String {
    match ft {
        FieldType::Named(name) => {
            if let Some(bt) = resolve_named_type(name, schema) {
                proto_base_type(&bt)
            } else {
                match name.as_str() {
                    "Price" | "Quantity" => "double".to_string(),
                    "TradeTimestamp" => "int64".to_string(),
                    _ => "string".to_string(),
                }
            }
        }
        FieldType::Enum(_) => "int32".to_string(),
        FieldType::List(inner) => format!(
            "repeated {}",
            proto_field_type(inner, schema, msg_name, false)
        ),
        FieldType::InlineStruct(_) => format!("{}{}", msg_name, pascal_case("inline")),
        FieldType::InlineBase(bt, _) => proto_base_type(bt),
    }
}

fn sbe_xml_base_type(bt: &BaseType) -> String {
    match bt {
        BaseType::String => "string".to_string(),
        BaseType::Int8 => "int8".to_string(),
        BaseType::Int16 => "int16".to_string(),
        BaseType::Int32 => "int32".to_string(),
        BaseType::Int64 => "int64".to_string(),
        BaseType::UInt8 => "uint8".to_string(),
        BaseType::UInt16 => "uint16".to_string(),
        BaseType::UInt32 => "uint32".to_string(),
        BaseType::UInt64 => "uint64".to_string(),
        BaseType::Float32 => "float".to_string(),
        BaseType::Float64 | BaseType::Decimal64 => "double".to_string(),
        BaseType::Bool => "uint8".to_string(),
        BaseType::Bytes => "varData".to_string(),
        BaseType::List(_) => "groupSizeEncoding".to_string(),
    }
}

fn sbe_xml_field_type(ft: &FieldType, schema: &Schema) -> String {
    match ft {
        FieldType::Named(name) => {
            if let Some(bt) = resolve_named_type(name, schema) {
                sbe_xml_base_type(&bt)
            } else {
                match name.as_str() {
                    "Price" | "Quantity" => "double".to_string(),
                    "TradeTimestamp" => "int64".to_string(),
                    _ => "string".to_string(),
                }
            }
        }
        FieldType::Enum(_) => "uint8".to_string(),
        FieldType::List(_) => "groupSizeEncoding".to_string(),
        FieldType::InlineStruct(_) => "composite".to_string(),
        FieldType::InlineBase(bt, _) => sbe_xml_base_type(bt),
    }
}

fn cpp_base_type(bt: &BaseType) -> String {
    match bt {
        BaseType::String => "std::string".to_string(),
        BaseType::Int8 => "int8_t".to_string(),
        BaseType::Int16 => "int16_t".to_string(),
        BaseType::Int32 => "int32_t".to_string(),
        BaseType::Int64 => "int64_t".to_string(),
        BaseType::UInt8 => "uint8_t".to_string(),
        BaseType::UInt16 => "uint16_t".to_string(),
        BaseType::UInt32 => "uint32_t".to_string(),
        BaseType::UInt64 => "uint64_t".to_string(),
        BaseType::Float32 => "float".to_string(),
        BaseType::Float64 | BaseType::Decimal64 => "double".to_string(),
        BaseType::Bool => "bool".to_string(),
        BaseType::Bytes => "std::vector<uint8_t>".to_string(),
        BaseType::List(inner) => format!("std::vector<{}>", cpp_base_type(inner)),
    }
}

fn cpp_field_type_named(
    ft: &FieldType,
    schema: &Schema,
    parent: &str,
    optional: bool,
    field_name: &str,
) -> String {
    let base = match ft {
        FieldType::Named(name) => {
            if schema
                .type_defs
                .iter()
                .any(|td| td.name == *name && td.fields.is_some())
            {
                name.clone()
            } else if let Some(bt) = resolve_named_type(name, schema) {
                cpp_base_type(&bt)
            } else {
                match name.as_str() {
                    "Price" | "Quantity" => "double".to_string(),
                    "TradeTimestamp" => "int64_t".to_string(),
                    _ => "std::string".to_string(),
                }
            }
        }
        FieldType::Enum(_) => canonical_enum_name(field_name, parent),
        FieldType::List(inner) => {
            format!(
                "std::vector<{}>",
                cpp_field_type_named(inner, schema, parent, false, field_name)
            )
        }
        FieldType::InlineStruct(_) => parent.to_string(),
        FieldType::InlineBase(bt, _) => cpp_base_type(bt),
    };
    if optional {
        format!("std::optional<{}>", base)
    } else {
        base
    }
}

fn csharp_base_type(bt: &BaseType) -> String {
    match bt {
        BaseType::String => "string".to_string(),
        BaseType::Int8 => "sbyte".to_string(),
        BaseType::Int16 => "short".to_string(),
        BaseType::Int32 => "int".to_string(),
        BaseType::Int64 => "long".to_string(),
        BaseType::UInt8 => "byte".to_string(),
        BaseType::UInt16 => "ushort".to_string(),
        BaseType::UInt32 => "uint".to_string(),
        BaseType::UInt64 => "ulong".to_string(),
        BaseType::Float32 => "float".to_string(),
        BaseType::Float64 | BaseType::Decimal64 => "double".to_string(),
        BaseType::Bool => "bool".to_string(),
        BaseType::Bytes => "byte[]".to_string(),
        BaseType::List(inner) => format!("List<{}>", csharp_base_type(inner)),
    }
}

fn csharp_field_type_named(
    ft: &FieldType,
    schema: &Schema,
    parent: &str,
    optional: bool,
    field_name: &str,
) -> String {
    let base = match ft {
        FieldType::Named(name) => {
            if schema
                .type_defs
                .iter()
                .any(|td| td.name == *name && td.fields.is_some())
            {
                name.clone()
            } else if let Some(bt) = resolve_named_type(name, schema) {
                csharp_base_type(&bt)
            } else {
                match name.as_str() {
                    "Price" | "Quantity" => "double".to_string(),
                    "TradeTimestamp" => "long".to_string(),
                    _ => "string".to_string(),
                }
            }
        }
        FieldType::Enum(_) => canonical_enum_name(field_name, parent),
        FieldType::List(inner) => {
            format!(
                "List<{}>",
                csharp_field_type_named(inner, schema, parent, false, field_name)
            )
        }
        FieldType::InlineStruct(_) => parent.to_string(),
        FieldType::InlineBase(bt, _) => csharp_base_type(bt),
    };
    if optional {
        format!("{}?", base)
    } else {
        base
    }
}

impl PythonCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "# Auto-generated by fig-fsl from schema '{}' v{}\n\n",
            schema.name, schema.version
        ));
        out.push_str("from dataclasses import dataclass\n");
        out.push_str("from enum import Enum\n");
        out.push_str("from typing import Optional\n\n");

        for (name, variants) in collect_shared_enums(schema) {
            out.push_str(&format!("class {name}(Enum):\n"));
            for (i, variant) in variants.iter().enumerate() {
                out.push_str(&format!("    {} = {}\n", pascal_case(variant), i + 1));
            }
            out.push('\n');
        }

        for td in &schema.type_defs {
            if let Some(fields) = &td.fields {
                out.push_str(&format!("# Struct: {}\n", td.name));
                out.push_str("# @dataclass\n");
                out.push_str(&format!("class {}:\n", td.name));
                for field in fields {
                    let py_type = python_field_type_named(
                        &field.field_type,
                        schema,
                        field.optional,
                        &td.name,
                        &field.name,
                    );
                    out.push_str(&format!("    {}: {}\n", field.name, py_type));
                }
                out.push('\n');
            }
        }

        for msg in &schema.messages {
            out.push_str(&format!("# Message: {}\n", msg.name));
            out.push_str(&format!("@dataclass\nclass {}:\n", msg.name));
            for field in &msg.fields {
                let py_type = python_field_type_named(
                    &field.field_type,
                    schema,
                    field.optional,
                    &msg.name,
                    &field.name,
                );
                out.push_str(&format!("    {}: {}\n", field.name, py_type));
            }
            out.push('\n');
        }
        out
    }
}

impl TypeScriptCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "// Auto-generated by fig-fsl from schema '{}' v{}\n\n",
            schema.name, schema.version
        ));

        for td in &schema.type_defs {
            if td.fields.is_none() {
                out.push_str(&format_type_alias_comment(td));
                out.push_str(&format!(
                    "export type {} = {};\n\n",
                    td.name,
                    ts_type_alias_base(td)
                ));
            }
        }

        for (name, variants) in collect_shared_enums(schema) {
            out.push_str(&format!("export type {} = ", name));
            out.push_str(
                &variants
                    .iter()
                    .map(|v| format!("\"{}\"", pascal_case(v)))
                    .collect::<Vec<_>>()
                    .join(" | "),
            );
            out.push('\n');
            out.push_str(&format!("export const {}Values = [", name));
            out.push_str(
                &variants
                    .iter()
                    .map(|v| format!("\"{}\"", pascal_case(v)))
                    .collect::<Vec<_>>()
                    .join(", "),
            );
            out.push_str("] as const;\n\n");
        }

        for td in &schema.type_defs {
            if let Some(fields) = &td.fields {
                out.push_str(&format!("// Struct: {}\n", td.name));
                out.push_str(&format!("export interface {} {{\n", td.name));
                for field in fields {
                    let ts_type = ts_field_type_named(
                        &field.field_type,
                        schema,
                        &td.name,
                        field.optional,
                        &field.name,
                    );
                    out.push_str(&format!("  {}: {};\n", field.name, ts_type));
                }
                out.push_str("}\n\n");
            }
        }

        for msg in &schema.messages {
            out.push_str(&format!("// Message: {}\n", msg.name));
            out.push_str(&message_metadata_constants_ts(msg, schema.well_known_id));
            out.push_str(&format!("export interface {} {{\n", msg.name));
            for field in &msg.fields {
                let ts_type = ts_field_type_named(
                    &field.field_type,
                    schema,
                    &msg.name,
                    field.optional,
                    &field.name,
                );
                out.push_str(&format!("  {}: {};\n", field.name, ts_type));
            }
            out.push_str("}\n\n");
        }
        out
    }
}

impl OcamlCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "(* Auto-generated by fig-fsl from schema '{}' v{} *)\n\n",
            schema.name, schema.version
        ));

        for td in &schema.type_defs {
            if td.fields.is_none() {
                out.push_str(&format!("(* {} *)\n", format_type_alias_comment(td).trim()));
                out.push_str(&format!(
                    "type {} = {}\n\n",
                    td.name,
                    ocaml_type_alias_base(td)
                ));
            }
        }

        for (name, variants) in collect_shared_enums(schema) {
            out.push_str(&format!("type {} =\n", name));
            for (i, variant) in variants.iter().enumerate() {
                let sep = if i + 1 == variants.len() { "" } else { " |" };
                out.push_str(&format!("  {} {sep}\n", pascal_case(variant)));
            }
            out.push('\n');
        }

        for td in &schema.type_defs {
            if let Some(fields) = &td.fields {
                out.push_str(&format!("(* Struct: {} *)\n", td.name));
                out.push_str(&format!("type {} = {{\n", td.name));
                for field in fields {
                    let ocaml_type = ocaml_field_type_named(
                        &field.field_type,
                        schema,
                        &td.name,
                        field.optional,
                        &field.name,
                    );
                    out.push_str(&format!("  {}: {};\n", field.name, ocaml_type));
                }
                out.push_str("}\n\n");
            }
        }

        for msg in &schema.messages {
            let type_name = snake_to_camel(&msg.name);
            out.push_str(&format!("(* Message: {} *)\n", msg.name));
            out.push_str(&format!(
                "let {}_channel_type = \"{}\"\n",
                msg.name,
                channel_type_str(&msg.channel_type)
            ));
            if let Some(cf) = &msg.correlation_field {
                out.push_str(&format!("let {}_correlation_field = \"{cf}\"\n", msg.name));
            }
            out.push_str(&format!("(* {} *)\n", cbor_fields_comment(msg).trim()));
            out.push_str(&format!("type {} = {{\n", type_name));
            for field in &msg.fields {
                let ocaml_type = ocaml_field_type_named(
                    &field.field_type,
                    schema,
                    &msg.name,
                    field.optional,
                    &field.name,
                );
                out.push_str(&format!("  {}: {};\n", field.name, ocaml_type));
            }
            out.push_str("}\n\n");
        }
        out
    }
}

impl ZigCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "// Auto-generated by fig-fsl from schema '{}' v{}\n\n",
            schema.name, schema.version
        ));

        for td in &schema.type_defs {
            if td.fields.is_none() {
                out.push_str(&format_type_alias_comment(td));
                out.push_str(&format!(
                    "pub const {} = {};\n\n",
                    td.name,
                    zig_type_alias_base(td)
                ));
            }
        }

        for (name, variants) in collect_shared_enums(schema) {
            out.push_str(&format!("pub const {name} = enum(u8) {{\n"));
            for (i, variant) in variants.iter().enumerate() {
                out.push_str(&format!("    {} = {},\n", pascal_case(variant), i + 1));
            }
            out.push_str("};\n\n");
        }

        for td in &schema.type_defs {
            if let Some(fields) = &td.fields {
                out.push_str(&format!("// Struct: {}\n", td.name));
                out.push_str(&format!("pub const {} = struct {{\n", td.name));
                for field in fields {
                    let zig_type = zig_field_type_named(
                        &field.field_type,
                        schema,
                        &td.name,
                        field.optional,
                        &field.name,
                    );
                    out.push_str(&format!("    {}: {},\n", field.name, zig_type));
                }
                out.push_str("};\n\n");
            }
        }

        for msg in &schema.messages {
            out.push_str(&format!("// Message: {}\n", msg.name));
            out.push_str(&format!(
                "pub const {}ChannelType = \"{}\";\n",
                msg.name,
                channel_type_str(&msg.channel_type)
            ));
            if let Some(cf) = &msg.correlation_field {
                out.push_str(&format!(
                    "pub const {}CorrelationField = \"{cf}\";\n",
                    msg.name
                ));
            }
            out.push_str(&cbor_fields_comment(msg));
            out.push_str(&format!("pub const {} = struct {{\n", msg.name));
            for field in &msg.fields {
                let zig_type = zig_field_type_named(
                    &field.field_type,
                    schema,
                    &msg.name,
                    field.optional,
                    &field.name,
                );
                out.push_str(&format!("    {}: {},\n", field.name, zig_type));
            }
            out.push_str("};\n\n");
        }
        out
    }
}

impl JavaCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "// Auto-generated by fig-fsl from schema '{}' v{}\n\n",
            schema.name, schema.version
        ));
        out.push_str("package generated;\n\n");
        out.push_str("import java.util.List;\n\n");

        for td in &schema.type_defs {
            if td.fields.is_none() {
                out.push_str(&format_type_alias_comment(td));
                out.push_str(&format!(
                    "public @interface {} {{ /* {} */ }}\n\n",
                    td.name,
                    java_type_alias_base(td)
                ));
            }
        }

        for (name, variants) in collect_shared_enums(schema) {
            out.push_str(&format!("public enum {} {{\n", name));
            for (i, variant) in variants.iter().enumerate() {
                let suffix = if i + 1 == variants.len() { ";" } else { "," };
                out.push_str(&format!(
                    "    {}({}){}\n",
                    pascal_case(variant),
                    i + 1,
                    suffix
                ));
            }
            out.push_str("    public final int wireValue;\n");
            out.push_str(&format!(
                "    {}(int wireValue) {{ this.wireValue = wireValue; }}\n",
                name
            ));
            out.push_str("}\n\n");
        }

        for td in &schema.type_defs {
            if let Some(fields) = &td.fields {
                out.push_str(&format!("// Struct: {}\n", td.name));
                out.push_str(&format!("public class {} {{\n", td.name));
                for field in fields {
                    let java_type = java_field_type_named(
                        &field.field_type,
                        schema,
                        &td.name,
                        field.optional,
                        &field.name,
                    );
                    out.push_str(&format!(
                        "    public {} {};\n",
                        java_type,
                        snake_to_camel(&field.name)
                    ));
                }
                out.push_str("}\n\n");
            }
        }

        for msg in &schema.messages {
            out.push_str(&format!("// Message: {}\n", msg.name));
            out.push_str(&format!(
                "public static final String {}MessageName = \"{}\";\n",
                msg.name, msg.name
            ));
            out.push_str(&format!(
                "public static final String {}ChannelType = \"{}\";\n",
                msg.name,
                channel_type_str(&msg.channel_type)
            ));
            if let Some(cf) = &msg.correlation_field {
                out.push_str(&format!(
                    "public static final String {}CorrelationField = \"{cf}\";\n",
                    msg.name
                ));
            }
            if let Some(id) = schema.well_known_id {
                out.push_str(&format!(
                    "public static final int {}SchemaId = 0x{id:02x};\n",
                    msg.name
                ));
            }
            out.push_str(&cbor_fields_comment(msg));
            out.push_str(&format!("public class {} {{\n", msg.name));
            for field in &msg.fields {
                let java_type = java_field_type_named(
                    &field.field_type,
                    schema,
                    &msg.name,
                    field.optional,
                    &field.name,
                );
                out.push_str(&format!(
                    "    public {} {};\n",
                    java_type,
                    snake_to_camel(&field.name)
                ));
            }
            out.push_str("}\n\n");
        }
        out
    }
}

impl JsonSchemaCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "{{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"title\": \"{}\",\n  \"version\": \"{}\",\n  \"definitions\": {{\n",
            schema.name, schema.version
        ));

        for (i, msg) in schema.messages.iter().enumerate() {
            out.push_str(&format!(
                "    \"{}\": {{\n      \"type\": \"object\",\n      \"properties\": {{\n",
                msg.name
            ));
            for field in &msg.fields {
                let json_type = json_schema_type(&field.field_type, schema);
                out.push_str(&format!(
                    "        \"{}\": {{ \"type\": \"{}\" }},\n",
                    field.name, json_type
                ));
            }
            out.push_str("      }\n    }");
            if i + 1 < schema.messages.len() {
                out.push(',');
            }
            out.push('\n');
        }
        out.push_str("  }\n}\n");
        out
    }
}

impl FixYamlCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "# Auto-generated FIX mapping for schema '{}' v{}\n",
            schema.name, schema.version
        ));
        out.push_str("fix_version: \"4.4\"\n");
        out.push_str("gateway: fig\n\n");
        out.push_str("messages:\n");

        for msg in &schema.messages {
            out.push_str(&format!("  - fig_message: {}\n", msg.name));
            out.push_str("    fix_msg_type: \"D\"\n");
            out.push_str("    fields:\n");
            for field in &msg.fields {
                let fix_tag = field.number.unwrap_or(0);
                out.push_str(&format!(
                    "      - fig: {}\n        fix_tag: {}\n",
                    field.name, fix_tag
                ));
            }
            out.push('\n');
        }
        out
    }
}

fn python_base_type(bt: &BaseType) -> String {
    match bt {
        BaseType::String | BaseType::Bytes => "str".to_string(),
        BaseType::Bool => "bool".to_string(),
        BaseType::Float32 | BaseType::Float64 | BaseType::Decimal64 => "float".to_string(),
        BaseType::Int8
        | BaseType::Int16
        | BaseType::Int32
        | BaseType::Int64
        | BaseType::UInt8
        | BaseType::UInt16
        | BaseType::UInt32
        | BaseType::UInt64 => "int".to_string(),
        BaseType::List(_) => "list".to_string(),
    }
}

fn ts_base_type(bt: &BaseType) -> String {
    match bt {
        BaseType::String | BaseType::Bytes => "string".to_string(),
        BaseType::Bool => "boolean".to_string(),
        BaseType::Float32 | BaseType::Float64 | BaseType::Decimal64 => "number".to_string(),
        BaseType::Int8
        | BaseType::Int16
        | BaseType::Int32
        | BaseType::Int64
        | BaseType::UInt8
        | BaseType::UInt16
        | BaseType::UInt32
        | BaseType::UInt64 => "number".to_string(),
        BaseType::List(inner) => format!("{}[]", ts_base_type(inner)),
    }
}

fn ts_field_type_named(
    ft: &FieldType,
    schema: &Schema,
    parent: &str,
    optional: bool,
    field_name: &str,
) -> String {
    let base = match ft {
        FieldType::Named(name) => {
            if schema
                .type_defs
                .iter()
                .any(|td| td.name == *name && td.fields.is_some())
            {
                name.clone()
            } else if resolve_named_type(name, schema).is_some() {
                ts_type_alias_base(&TypeDef {
                    name: name.clone(),
                    base_type: resolve_named_type(name, schema),
                    constraints: vec![],
                    fields: None,
                })
                .to_string()
            } else {
                "string".to_string()
            }
        }
        FieldType::Enum(_) => canonical_enum_name(field_name, parent),
        FieldType::List(inner) => format!(
            "{}[]",
            ts_field_type_named(inner, schema, parent, false, field_name)
        ),
        FieldType::InlineStruct(_) => "Record<string, unknown>".to_string(),
        FieldType::InlineBase(bt, _) => ts_base_type(bt),
    };
    if optional {
        format!("{base} | null")
    } else {
        base
    }
}

fn ocaml_field_type_named(
    ft: &FieldType,
    schema: &Schema,
    parent: &str,
    optional: bool,
    field_name: &str,
) -> String {
    let base = match ft {
        FieldType::Named(name) => {
            if schema
                .type_defs
                .iter()
                .any(|td| td.name == *name && td.fields.is_some())
            {
                name.clone()
            } else if let Some(bt) = resolve_named_type(name, schema) {
                ocaml_base_type(&bt)
            } else {
                name.clone()
            }
        }
        FieldType::Enum(_) => canonical_enum_name(field_name, parent),
        FieldType::List(inner) => format!(
            "{} list",
            ocaml_field_type_named(inner, schema, parent, false, field_name)
        ),
        FieldType::InlineStruct(_) => parent.to_string(),
        FieldType::InlineBase(bt, _) => ocaml_base_type(bt),
    };
    if optional {
        format!("{base} option")
    } else {
        base
    }
}

fn zig_field_type_named(
    ft: &FieldType,
    schema: &Schema,
    parent: &str,
    optional: bool,
    field_name: &str,
) -> String {
    let base = match ft {
        FieldType::Named(name) => {
            if schema
                .type_defs
                .iter()
                .any(|td| td.name == *name && td.fields.is_some())
            {
                name.clone()
            } else if let Some(bt) = resolve_named_type(name, schema) {
                zig_base_type(&bt)
            } else {
                "[]const u8".to_string()
            }
        }
        FieldType::Enum(_) => canonical_enum_name(field_name, parent),
        FieldType::List(inner) => format!(
            "[]const {}",
            zig_field_type_named(inner, schema, parent, false, field_name)
        ),
        FieldType::InlineStruct(_) => parent.to_string(),
        FieldType::InlineBase(bt, _) => zig_base_type(bt),
    };
    if optional {
        format!("?{base}")
    } else {
        base
    }
}

fn java_field_type_named(
    ft: &FieldType,
    schema: &Schema,
    parent: &str,
    optional: bool,
    field_name: &str,
) -> String {
    let base = match ft {
        FieldType::Named(name) => {
            if schema
                .type_defs
                .iter()
                .any(|td| td.name == *name && td.fields.is_some())
            {
                name.clone()
            } else if let Some(bt) = resolve_named_type(name, schema) {
                java_type_alias_base(&TypeDef {
                    name: name.clone(),
                    base_type: Some(bt),
                    constraints: vec![],
                    fields: None,
                })
                .to_string()
            } else {
                "String".to_string()
            }
        }
        FieldType::Enum(_) => canonical_enum_name(field_name, parent),
        FieldType::List(inner) => format!(
            "List<{}>",
            java_field_type_named(inner, schema, parent, false, field_name)
        ),
        FieldType::InlineStruct(_) => parent.to_string(),
        FieldType::InlineBase(bt, _) => java_type_alias_base(&TypeDef {
            name: String::new(),
            base_type: Some(bt.clone()),
            constraints: vec![],
            fields: None,
        })
        .to_string(),
    };
    if optional {
        format!("{base} /* optional */")
    } else {
        base
    }
}

fn ocaml_base_type(bt: &BaseType) -> String {
    match bt {
        BaseType::String | BaseType::Bytes => "string".to_string(),
        BaseType::Bool => "bool".to_string(),
        BaseType::Float32 | BaseType::Float64 | BaseType::Decimal64 => "float".to_string(),
        BaseType::Int8 | BaseType::Int16 | BaseType::Int32 => "int".to_string(),
        BaseType::Int64
        | BaseType::UInt8
        | BaseType::UInt16
        | BaseType::UInt32
        | BaseType::UInt64 => "int64".to_string(),
        BaseType::List(_) => "string list".to_string(),
    }
}

fn zig_base_type(bt: &BaseType) -> String {
    match bt {
        BaseType::String | BaseType::Bytes => "[]const u8".to_string(),
        BaseType::Bool => "bool".to_string(),
        BaseType::Float32 => "f32".to_string(),
        BaseType::Float64 | BaseType::Decimal64 => "f64".to_string(),
        BaseType::Int8 => "i8".to_string(),
        BaseType::Int16 => "i16".to_string(),
        BaseType::Int32 => "i32".to_string(),
        BaseType::Int64 => "i64".to_string(),
        BaseType::UInt8 => "u8".to_string(),
        BaseType::UInt16 => "u16".to_string(),
        BaseType::UInt32 => "u32".to_string(),
        BaseType::UInt64 => "u64".to_string(),
        BaseType::List(_) => "[]const u8".to_string(),
    }
}

fn json_schema_type(ft: &FieldType, schema: &Schema) -> &'static str {
    match ft {
        FieldType::Named(name) => {
            if let Some(bt) = resolve_named_type(name, schema) {
                match bt {
                    BaseType::String | BaseType::Bytes => "string",
                    BaseType::Bool => "boolean",
                    _ => "number",
                }
            } else {
                "string"
            }
        }
        FieldType::Enum(_) => "integer",
        FieldType::List(_) => "array",
        FieldType::InlineStruct(_) => "object",
        FieldType::InlineBase(bt, _) => match bt {
            BaseType::String | BaseType::Bytes => "string",
            BaseType::Bool => "boolean",
            BaseType::List(_) => "array",
            _ => "number",
        },
    }
}
