//! Multi-target schema codegen (Go, Protobuf, SBE XML, C++, C#).
//!
//! Generates message struct definitions from FSL AST — focused on
//! `schema.messages` fields with BaseType → target type mapping.

use crate::ast::*;

/// Go struct generator with JSON tags
pub struct GoCodegen;

/// Protobuf `.proto` file generator
pub struct ProtoCodegen;

/// SBE XML `messageSchema` generator
pub struct SbeXmlCodegen;

/// C++ struct generator
pub struct CppCodegen;

/// C# class generator
pub struct CsharpCodegen;

/// Python dataclass generator
pub struct PythonCodegen;

/// TypeScript interface generator
pub struct TypeScriptCodegen;

/// OCaml record generator
pub struct OcamlCodegen;

/// Zig struct generator
pub struct ZigCodegen;

/// JSON Schema generator
pub struct JsonSchemaCodegen;

/// FIX mapping YAML generator
pub struct FixYamlCodegen;

impl GoCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        let desc = schema
            .description
            .as_deref()
            .unwrap_or(&schema.name);
        out.push_str(&format!(
            "// Auto-generated by fig-fsl from schema '{}' v{}\n",
            schema.name, schema.version
        ));
        out.push_str(&format!("// {}\n\n", desc));
        out.push_str("package generated\n\n");

        for msg in &schema.messages {
            out.push_str(&format!("// Message: {}\n", msg.name));
            out.push_str(&format!("type {} struct {{\n", msg.name));
            for field in &msg.fields {
                let go_type = go_field_type(&field.field_type, schema, &msg.name, field.optional);
                let field_name = pascal_case(&field.name);
                out.push_str(&format!(
                    "    {} {} `json:\"{}\"`\n",
                    field_name, go_type, field.name
                ));
            }
            out.push_str("}\n\n");
        }
        out
    }
}

impl ProtoCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        let desc = schema
            .description
            .as_deref()
            .unwrap_or(&schema.name);
        out.push_str(&format!(
            "// Auto-generated by fig-fsl from schema '{}' v{}\n",
            schema.name, schema.version
        ));
        out.push_str(&format!("// {}\n\n", desc));
        out.push_str("syntax = \"proto3\";\n\n");
        out.push_str(&format!("package {};\n\n", proto_package_name(&schema.name)));

        for msg in &schema.messages {
            out.push_str(&format!("// Message: {}\n", msg.name));
            out.push_str(&format!("message {} {{\n", msg.name));
            for field in &msg.fields {
                let proto_type =
                    proto_field_type(&field.field_type, schema, &msg.name, field.optional);
                let number = field.number.unwrap_or(0);
                if field.optional {
                    out.push_str(&format!(
                        "  optional {} {} = {};\n",
                        proto_type, field.name, number
                    ));
                } else {
                    out.push_str(&format!("  {} {} = {};\n", proto_type, field.name, number));
                }
            }
            out.push_str("}\n\n");
        }
        out
    }
}

impl SbeXmlCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        let desc = schema
            .description
            .as_deref()
            .unwrap_or(&schema.name);
        out.push_str(&format!(
            "<!-- Auto-generated by fig-fsl from schema '{}' v{} -->\n",
            schema.name, schema.version
        ));
        out.push_str(&format!("<!-- {} -->\n", desc));
        out.push_str(
            "<sbe:messageSchema xmlns:sbe=\"http://fixprotocol.io/2016/sbe\"\n",
        );
        out.push_str(&format!(
            "                   package=\"{}\"\n",
            schema.name.replace('.', "_")
        ));
        let schema_id = schema.well_known_id.unwrap_or(1);
        out.push_str(&format!("                   id=\"{}\"\n", schema_id));
        out.push_str("                   version=\"0\"\n");
        out.push_str(&format!(
            "                   semanticVersion=\"{}\"\n",
            schema.version
        ));
        out.push_str("                   byteOrder=\"littleEndian\">\n\n");
        out.push_str("  <types>\n");
        out.push_str("    <composite name=\"messageHeader\" description=\"Message identifiers and length of message root\">\n");
        out.push_str("      <type name=\"blockLength\" primitiveType=\"uint16\"/>\n");
        out.push_str("      <type name=\"templateId\" primitiveType=\"uint16\"/>\n");
        out.push_str("      <type name=\"schemaId\" primitiveType=\"uint16\"/>\n");
        out.push_str("      <type name=\"version\" primitiveType=\"uint16\"/>\n");
        out.push_str("    </composite>\n");
        out.push_str("  </types>\n\n");

        for (template_id, msg) in schema.messages.iter().enumerate() {
            let tid = template_id + 1;
            out.push_str(&format!("  <message name=\"{}\" id=\"{}\">\n", msg.name, tid));
            for field in &msg.fields {
                let sbe_type = sbe_xml_field_type(&field.field_type, schema);
                let presence = if field.optional { "optional" } else { "required" };
                let field_id = field.number.unwrap_or(0);
                let sbe_name = snake_to_camel(&field.name);
                out.push_str(&format!(
                    "    <field name=\"{}\" id=\"{}\" type=\"{}\" presence=\"{}\"/>\n",
                    sbe_name, field_id, sbe_type, presence
                ));
            }
            out.push_str("  </message>\n\n");
        }
        out.push_str("</sbe:messageSchema>\n");
        out
    }
}

impl CppCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        let desc = schema
            .description
            .as_deref()
            .unwrap_or(&schema.name);
        out.push_str(&format!(
            "// Auto-generated by fig-fsl from schema '{}' v{}\n",
            schema.name, schema.version
        ));
        out.push_str(&format!("// {}\n\n", desc));
        out.push_str("#include <cstdint>\n");
        out.push_str("#include <optional>\n");
        out.push_str("#include <string>\n");
        out.push_str("#include <vector>\n\n");

        for msg in &schema.messages {
            out.push_str(&format!("// Message: {}\n", msg.name));
            out.push_str(&format!("struct {} {{\n", msg.name));
            for field in &msg.fields {
                let cpp_type =
                    cpp_field_type(&field.field_type, schema, &msg.name, field.optional);
                out.push_str(&format!("    {} {};\n", cpp_type, field.name));
            }
            out.push_str("};\n\n");
        }
        out
    }
}

impl CsharpCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        let desc = schema
            .description
            .as_deref()
            .unwrap_or(&schema.name);
        out.push_str(&format!(
            "// Auto-generated by fig-fsl from schema '{}' v{}\n",
            schema.name, schema.version
        ));
        out.push_str(&format!("// {}\n\n", desc));
        out.push_str("using System.Collections.Generic;\n\n");
        out.push_str("namespace Generated\n{\n");

        for msg in &schema.messages {
            out.push_str(&format!("    // Message: {}\n", msg.name));
            out.push_str(&format!("    public class {}\n", msg.name));
            out.push_str("    {\n");
            for field in &msg.fields {
                let cs_type =
                    csharp_field_type(&field.field_type, schema, &msg.name, field.optional);
                let prop_name = snake_to_camel(&field.name);
                out.push_str(&format!(
                    "        public {} {} {{ get; set; }}\n",
                    cs_type, prop_name
                ));
            }
            out.push_str("    }\n\n");
        }
        out.push_str("}\n");
        out
    }
}

// ── Shared helpers ──────────────────────────────────────────────

fn pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

fn snake_to_camel(s: &str) -> String {
    let parts: Vec<&str> = s.split('_').collect();
    if parts.is_empty() {
        return String::new();
    }
    let first = parts[0];
    let rest = parts
        .iter()
        .skip(1)
        .map(|p| pascal_case(p))
        .collect::<Vec<_>>()
        .join("");
    format!("{}{}", first, rest)
}

fn proto_package_name(name: &str) -> String {
    name.replace('.', "_")
}

fn resolve_named_type(name: &str, schema: &Schema) -> Option<BaseType> {
    schema
        .type_defs
        .iter()
        .find(|td| td.name == name)
        .and_then(|td| td.base_type.clone())
}

fn go_base_type(bt: &BaseType) -> String {
    match bt {
        BaseType::String => "string".to_string(),
        BaseType::Int8 => "int8".to_string(),
        BaseType::Int16 => "int16".to_string(),
        BaseType::Int32 => "int32".to_string(),
        BaseType::Int64 => "int64".to_string(),
        BaseType::UInt8 => "uint8".to_string(),
        BaseType::UInt16 => "uint16".to_string(),
        BaseType::UInt32 => "uint32".to_string(),
        BaseType::UInt64 => "uint64".to_string(),
        BaseType::Float32 => "float32".to_string(),
        BaseType::Float64 => "float64".to_string(),
        BaseType::Decimal64 => "float64".to_string(),
        BaseType::Bool => "bool".to_string(),
        BaseType::Bytes => "[]byte".to_string(),
        BaseType::List(inner) => format!("[]{}", go_base_type(inner)),
    }
}

fn go_field_type(ft: &FieldType, schema: &Schema, msg_name: &str, optional: bool) -> String {
    let base = match ft {
        FieldType::Named(name) => {
            if let Some(bt) = resolve_named_type(name, schema) {
                go_base_type(&bt)
            } else {
                match name.as_str() {
                    "Price" | "Quantity" => "float64".to_string(),
                    "TradeTimestamp" => "int64".to_string(),
                    _ => "string".to_string(),
                }
            }
        }
        FieldType::Enum(_) => "int32".to_string(),
        FieldType::List(inner) => format!("[]{}", go_field_type(inner, schema, msg_name, false)),
        FieldType::InlineStruct(_) => format!("{}{}", msg_name, pascal_case("inline")),
        FieldType::InlineBase(bt, _) => go_base_type(bt),
    };
    if optional {
        format!("*{}", base)
    } else {
        base
    }
}

fn proto_base_type(bt: &BaseType) -> String {
    match bt {
        BaseType::String => "string".to_string(),
        BaseType::Int8 | BaseType::Int16 | BaseType::Int32 => "int32".to_string(),
        BaseType::Int64 => "int64".to_string(),
        BaseType::UInt8 | BaseType::UInt16 | BaseType::UInt32 => "uint32".to_string(),
        BaseType::UInt64 => "uint64".to_string(),
        BaseType::Float32 => "float".to_string(),
        BaseType::Float64 | BaseType::Decimal64 => "double".to_string(),
        BaseType::Bool => "bool".to_string(),
        BaseType::Bytes => "bytes".to_string(),
        BaseType::List(inner) => format!("repeated {}", proto_base_type(inner)),
    }
}

fn proto_field_type(ft: &FieldType, schema: &Schema, msg_name: &str, _optional: bool) -> String {
    match ft {
        FieldType::Named(name) => {
            if let Some(bt) = resolve_named_type(name, schema) {
                proto_base_type(&bt)
            } else {
                match name.as_str() {
                    "Price" | "Quantity" => "double".to_string(),
                    "TradeTimestamp" => "int64".to_string(),
                    _ => "string".to_string(),
                }
            }
        }
        FieldType::Enum(_) => "int32".to_string(),
        FieldType::List(inner) => format!("repeated {}", proto_field_type(inner, schema, msg_name, false)),
        FieldType::InlineStruct(_) => format!("{}{}", msg_name, pascal_case("inline")),
        FieldType::InlineBase(bt, _) => proto_base_type(bt),
    }
}

fn sbe_xml_base_type(bt: &BaseType) -> String {
    match bt {
        BaseType::String => "string".to_string(),
        BaseType::Int8 => "int8".to_string(),
        BaseType::Int16 => "int16".to_string(),
        BaseType::Int32 => "int32".to_string(),
        BaseType::Int64 => "int64".to_string(),
        BaseType::UInt8 => "uint8".to_string(),
        BaseType::UInt16 => "uint16".to_string(),
        BaseType::UInt32 => "uint32".to_string(),
        BaseType::UInt64 => "uint64".to_string(),
        BaseType::Float32 => "float".to_string(),
        BaseType::Float64 | BaseType::Decimal64 => "double".to_string(),
        BaseType::Bool => "uint8".to_string(),
        BaseType::Bytes => "varData".to_string(),
        BaseType::List(_) => "groupSizeEncoding".to_string(),
    }
}

fn sbe_xml_field_type(ft: &FieldType, schema: &Schema) -> String {
    match ft {
        FieldType::Named(name) => {
            if let Some(bt) = resolve_named_type(name, schema) {
                sbe_xml_base_type(&bt)
            } else {
                match name.as_str() {
                    "Price" | "Quantity" => "double".to_string(),
                    "TradeTimestamp" => "int64".to_string(),
                    _ => "string".to_string(),
                }
            }
        }
        FieldType::Enum(_) => "uint8".to_string(),
        FieldType::List(_) => "groupSizeEncoding".to_string(),
        FieldType::InlineStruct(_) => "composite".to_string(),
        FieldType::InlineBase(bt, _) => sbe_xml_base_type(bt),
    }
}

fn cpp_base_type(bt: &BaseType) -> String {
    match bt {
        BaseType::String => "std::string".to_string(),
        BaseType::Int8 => "int8_t".to_string(),
        BaseType::Int16 => "int16_t".to_string(),
        BaseType::Int32 => "int32_t".to_string(),
        BaseType::Int64 => "int64_t".to_string(),
        BaseType::UInt8 => "uint8_t".to_string(),
        BaseType::UInt16 => "uint16_t".to_string(),
        BaseType::UInt32 => "uint32_t".to_string(),
        BaseType::UInt64 => "uint64_t".to_string(),
        BaseType::Float32 => "float".to_string(),
        BaseType::Float64 | BaseType::Decimal64 => "double".to_string(),
        BaseType::Bool => "bool".to_string(),
        BaseType::Bytes => "std::vector<uint8_t>".to_string(),
        BaseType::List(inner) => format!("std::vector<{}>", cpp_base_type(inner)),
    }
}

fn cpp_field_type(ft: &FieldType, schema: &Schema, msg_name: &str, optional: bool) -> String {
    let base = match ft {
        FieldType::Named(name) => {
            if let Some(bt) = resolve_named_type(name, schema) {
                cpp_base_type(&bt)
            } else {
                match name.as_str() {
                    "Price" | "Quantity" => "double".to_string(),
                    "TradeTimestamp" => "int64_t".to_string(),
                    _ => "std::string".to_string(),
                }
            }
        }
        FieldType::Enum(_) => "uint8_t".to_string(),
        FieldType::List(inner) => {
            format!("std::vector<{}>", cpp_field_type(inner, schema, msg_name, false))
        }
        FieldType::InlineStruct(_) => format!("{}{}", msg_name, pascal_case("inline")),
        FieldType::InlineBase(bt, _) => cpp_base_type(bt),
    };
    if optional {
        format!("std::optional<{}>", base)
    } else {
        base
    }
}

fn csharp_base_type(bt: &BaseType) -> String {
    match bt {
        BaseType::String => "string".to_string(),
        BaseType::Int8 => "sbyte".to_string(),
        BaseType::Int16 => "short".to_string(),
        BaseType::Int32 => "int".to_string(),
        BaseType::Int64 => "long".to_string(),
        BaseType::UInt8 => "byte".to_string(),
        BaseType::UInt16 => "ushort".to_string(),
        BaseType::UInt32 => "uint".to_string(),
        BaseType::UInt64 => "ulong".to_string(),
        BaseType::Float32 => "float".to_string(),
        BaseType::Float64 | BaseType::Decimal64 => "double".to_string(),
        BaseType::Bool => "bool".to_string(),
        BaseType::Bytes => "byte[]".to_string(),
        BaseType::List(inner) => format!("List<{}>", csharp_base_type(inner)),
    }
}

fn csharp_field_type(ft: &FieldType, schema: &Schema, msg_name: &str, optional: bool) -> String {
    let base = match ft {
        FieldType::Named(name) => {
            if let Some(bt) = resolve_named_type(name, schema) {
                csharp_base_type(&bt)
            } else {
                match name.as_str() {
                    "Price" | "Quantity" => "double".to_string(),
                    "TradeTimestamp" => "long".to_string(),
                    _ => "string".to_string(),
                }
            }
        }
        FieldType::Enum(_) => "int".to_string(),
        FieldType::List(inner) => {
            format!("List<{}>", csharp_field_type(inner, schema, msg_name, false))
        }
        FieldType::InlineStruct(_) => format!("{}{}", msg_name, pascal_case("inline")),
        FieldType::InlineBase(bt, _) => csharp_base_type(bt),
    };
    if optional {
        format!("{}?", base)
    } else {
        base
    }
}

impl PythonCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "# Auto-generated by fig-fsl from schema '{}' v{}\n\n",
            schema.name, schema.version
        ));
        out.push_str("from dataclasses import dataclass\n");
        out.push_str("from typing import Optional\n\n");

        for msg in &schema.messages {
            out.push_str(&format!("# Message: {}\n", msg.name));
            out.push_str(&format!("@dataclass\nclass {}:\n", msg.name));
            for field in &msg.fields {
                let py_type = python_field_type(&field.field_type, schema, field.optional);
                out.push_str(&format!("    {}: {}\n", field.name, py_type));
            }
            out.push('\n');
        }
        out
    }
}

impl TypeScriptCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "// Auto-generated by fig-fsl from schema '{}' v{}\n\n",
            schema.name, schema.version
        ));

        for msg in &schema.messages {
            out.push_str(&format!("// Message: {}\n", msg.name));
            out.push_str(&format!("export interface {} {{\n", msg.name));
            for field in &msg.fields {
                let ts_type = ts_field_type(&field.field_type, schema, field.optional);
                out.push_str(&format!("  {}: {};\n", field.name, ts_type));
            }
            out.push_str("}\n\n");
        }
        out
    }
}

impl OcamlCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "(* Auto-generated by fig-fsl from schema '{}' v{} *)\n\n",
            schema.name, schema.version
        ));

        for msg in &schema.messages {
            let type_name = snake_to_camel(&msg.name);
            out.push_str(&format!("(* Message: {} *)\n", msg.name));
            out.push_str(&format!("type {} = {{\n", type_name));
            for field in &msg.fields {
                let ocaml_type = ocaml_field_type(&field.field_type, schema, field.optional);
                out.push_str(&format!("  {}: {};\n", field.name, ocaml_type));
            }
            out.push_str("}\n\n");
        }
        out
    }
}

impl ZigCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "// Auto-generated by fig-fsl from schema '{}' v{}\n\n",
            schema.name, schema.version
        ));

        for msg in &schema.messages {
            out.push_str(&format!("// Message: {}\n", msg.name));
            out.push_str(&format!("pub const {} = struct {{\n", msg.name));
            for field in &msg.fields {
                let zig_type = zig_field_type(&field.field_type, schema, field.optional);
                out.push_str(&format!("    {}: {},\n", field.name, zig_type));
            }
            out.push_str("};\n\n");
        }
        out
    }
}

impl JsonSchemaCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "{{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"title\": \"{}\",\n  \"version\": \"{}\",\n  \"definitions\": {{\n",
            schema.name, schema.version
        ));

        for (i, msg) in schema.messages.iter().enumerate() {
            out.push_str(&format!("    \"{}\": {{\n      \"type\": \"object\",\n      \"properties\": {{\n", msg.name));
            for field in &msg.fields {
                let json_type = json_schema_type(&field.field_type, schema);
                out.push_str(&format!(
                    "        \"{}\": {{ \"type\": \"{}\" }},\n",
                    field.name, json_type
                ));
            }
            out.push_str("      }\n    }");
            if i + 1 < schema.messages.len() {
                out.push(',');
            }
            out.push('\n');
        }
        out.push_str("  }\n}\n");
        out
    }
}

impl FixYamlCodegen {
    pub fn generate(schema: &Schema) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "# Auto-generated FIX mapping for schema '{}' v{}\n",
            schema.name, schema.version
        ));
        out.push_str("fix_version: \"4.4\"\n");
        out.push_str("gateway: fig\n\n");
        out.push_str("messages:\n");

        for msg in &schema.messages {
            out.push_str(&format!("  - fig_message: {}\n", msg.name));
            out.push_str("    fix_msg_type: \"D\"\n");
            out.push_str("    fields:\n");
            for field in &msg.fields {
                let fix_tag = field.number.unwrap_or(0);
                out.push_str(&format!(
                    "      - fig: {}\n        fix_tag: {}\n",
                    field.name, fix_tag
                ));
            }
            out.push('\n');
        }
        out
    }
}

fn python_base_type(bt: &BaseType) -> String {
    match bt {
        BaseType::String | BaseType::Bytes => "str".to_string(),
        BaseType::Bool => "bool".to_string(),
        BaseType::Float32 | BaseType::Float64 | BaseType::Decimal64 => "float".to_string(),
        BaseType::Int8 | BaseType::Int16 | BaseType::Int32 | BaseType::Int64
        | BaseType::UInt8 | BaseType::UInt16 | BaseType::UInt32 | BaseType::UInt64 => "int".to_string(),
        BaseType::List(_) => "list".to_string(),
    }
}

fn python_field_type(ft: &FieldType, schema: &Schema, optional: bool) -> String {
    let base = match ft {
        FieldType::Named(name) => {
            if let Some(bt) = resolve_named_type(name, schema) {
                python_base_type(&bt)
            } else {
                "str".to_string()
            }
        }
        FieldType::Enum(_) => "int".to_string(),
        FieldType::List(inner) => format!("list[{}]", python_field_type(inner, schema, false)),
        FieldType::InlineStruct(_) => "dict".to_string(),
        FieldType::InlineBase(bt, _) => python_base_type(bt),
    };
    if optional {
        format!("Optional[{}]", base)
    } else {
        base
    }
}

fn ts_base_type(bt: &BaseType) -> String {
    match bt {
        BaseType::String | BaseType::Bytes => "string".to_string(),
        BaseType::Bool => "boolean".to_string(),
        BaseType::Float32 | BaseType::Float64 | BaseType::Decimal64 => "number".to_string(),
        BaseType::Int8 | BaseType::Int16 | BaseType::Int32 | BaseType::Int64
        | BaseType::UInt8 | BaseType::UInt16 | BaseType::UInt32 | BaseType::UInt64 => "number".to_string(),
        BaseType::List(inner) => format!("{}[]", ts_base_type(inner)),
    }
}

fn ts_field_type(ft: &FieldType, schema: &Schema, optional: bool) -> String {
    let base = match ft {
        FieldType::Named(name) => {
            if let Some(bt) = resolve_named_type(name, schema) {
                ts_base_type(&bt)
            } else {
                "string".to_string()
            }
        }
        FieldType::Enum(_) => "number".to_string(),
        FieldType::List(inner) => format!("{}[]", ts_field_type(inner, schema, false)),
        FieldType::InlineStruct(_) => "Record<string, unknown>".to_string(),
        FieldType::InlineBase(bt, _) => ts_base_type(bt),
    };
    if optional {
        format!("{} | null", base)
    } else {
        base
    }
}

fn ocaml_base_type(bt: &BaseType) -> String {
    match bt {
        BaseType::String | BaseType::Bytes => "string".to_string(),
        BaseType::Bool => "bool".to_string(),
        BaseType::Float32 | BaseType::Float64 | BaseType::Decimal64 => "float".to_string(),
        BaseType::Int8 | BaseType::Int16 | BaseType::Int32 => "int".to_string(),
        BaseType::Int64 | BaseType::UInt8 | BaseType::UInt16 | BaseType::UInt32 | BaseType::UInt64 => "int64".to_string(),
        BaseType::List(_) => "string list".to_string(),
    }
}

fn ocaml_field_type(ft: &FieldType, schema: &Schema, optional: bool) -> String {
    let base = match ft {
        FieldType::Named(name) => {
            if let Some(bt) = resolve_named_type(name, schema) {
                ocaml_base_type(&bt)
            } else {
                "string".to_string()
            }
        }
        FieldType::Enum(_) => "int".to_string(),
        FieldType::List(_) => "string list".to_string(),
        FieldType::InlineStruct(_) => "string".to_string(),
        FieldType::InlineBase(bt, _) => ocaml_base_type(bt),
    };
    if optional {
        format!("{} option", base)
    } else {
        base
    }
}

fn zig_base_type(bt: &BaseType) -> String {
    match bt {
        BaseType::String | BaseType::Bytes => "[]const u8".to_string(),
        BaseType::Bool => "bool".to_string(),
        BaseType::Float32 => "f32".to_string(),
        BaseType::Float64 | BaseType::Decimal64 => "f64".to_string(),
        BaseType::Int8 => "i8".to_string(),
        BaseType::Int16 => "i16".to_string(),
        BaseType::Int32 => "i32".to_string(),
        BaseType::Int64 => "i64".to_string(),
        BaseType::UInt8 => "u8".to_string(),
        BaseType::UInt16 => "u16".to_string(),
        BaseType::UInt32 => "u32".to_string(),
        BaseType::UInt64 => "u64".to_string(),
        BaseType::List(_) => "[]const u8".to_string(),
    }
}

fn zig_field_type(ft: &FieldType, schema: &Schema, optional: bool) -> String {
    let base = match ft {
        FieldType::Named(name) => {
            if let Some(bt) = resolve_named_type(name, schema) {
                zig_base_type(&bt)
            } else {
                "[]const u8".to_string()
            }
        }
        FieldType::Enum(_) => "u8".to_string(),
        FieldType::List(_) => "[]const u8".to_string(),
        FieldType::InlineStruct(_) => "[]const u8".to_string(),
        FieldType::InlineBase(bt, _) => zig_base_type(bt),
    };
    if optional {
        format!("?{}", base)
    } else {
        base
    }
}

fn json_schema_type(ft: &FieldType, schema: &Schema) -> &'static str {
    match ft {
        FieldType::Named(name) => {
            if let Some(bt) = resolve_named_type(name, schema) {
                match bt {
                    BaseType::String | BaseType::Bytes => "string",
                    BaseType::Bool => "boolean",
                    _ => "number",
                }
            } else {
                "string"
            }
        }
        FieldType::Enum(_) => "integer",
        FieldType::List(_) => "array",
        FieldType::InlineStruct(_) => "object",
        FieldType::InlineBase(bt, _) => match bt {
            BaseType::String | BaseType::Bytes => "string",
            BaseType::Bool => "boolean",
            BaseType::List(_) => "array",
            _ => "number",
        },
    }
}
